
export type FAQ = {
    question: string;
    answer: string;
    related: string[];
};

export const faqs: FAQ[] = [
  {
    question: "I didn’t receive my verification email. What should I do?",
    answer: "First, check your spam or junk folder. In Gmail, open the menu and scroll to 'Spam'. If the email is there, mark it as 'Not Spam' and open the verification link. If it’s still missing, try resending it from the app or contact support.",
    related: ["What is the spam folder?", "How to open the spam folder?", "How to verify my email?"]
  },
  {
    question: "What is the spam folder?",
    answer: "The spam folder is where your email provider sends suspicious or promotional emails. Sometimes verification emails also land here.",
    related: ["How to open the spam folder?", "Why do emails go to spam?"]
  },
  {
    question: "How to open the spam folder?",
    answer: "In Gmail: open the app → tap the three horizontal lines (top-left menu) → scroll down → tap on 'Spam'. For other email providers, the folder is usually visible in the main menu.",
    related: ["How to verify my email?", "What is the spam folder?"]
  },
  {
    question: "How to verify my email?",
    answer: "Once you receive the verification email, open it and tap the link provided to activate your account. If not found, check spam or try to log in again to get a new verification prompt.",
    related: ["I didn’t receive my verification email.", "How to open the spam folder?"]
  },
  {
    question: "What are custom quizzes?",
    answer: "Custom quizzes are sets of questions created by our AI based on your specific inputs. You can select topics, subjects, difficulty level, and more to generate your own focused quizzes on almost any topic.",
    related: ["What is a study guide?", "What is the difference between practice questions and custom quizzes?"]
  },
  {
    question: "What is the difference between practice questions and custom quizzes?",
    answer: "Practice questions are for quick revisions on a topic and come with detailed explanations. Custom quizzes are more dynamic tests generated by AI based on a topic you enter, focusing purely on assessment.",
    related: ["What is a study guide?", "What are custom quizzes?"]
  },
  {
    question: "What is a study guide?",
    answer: "An AI-generated study guide is a structured document that breaks down a topic for you. It includes a summary, key concepts with definitions, simple analogies, and a quick self-quiz to help you learn effectively.",
    related: ["What are custom quizzes?", "What is the difference between practice questions and custom quizzes?"]
  },
  {
    question: "What is the difference between custom quizzes and entry tests like MDCAT/ECAT?",
    answer: "In custom quizzes, you enter your own topic (like 'Respiration') and the AI generates relevant questions with broader content. In MDCAT/ECAT mode, quizzes strictly follow the official test standards, syllabus, and difficulty level.",
    related: ["What are custom quizzes?", "What is MDCAT preparation?", "What are standard-based tests?"]
  },
    {
    question: "What are standard-based tests?",
    answer: "Standard-based tests (like our MDCAT, ECAT, and NTS modules) are designed to mimic the format, syllabus, and difficulty of official entrance exams. They are ideal for targeted exam preparation.",
    related: ["What is MDCAT preparation?", "What is ECAT prep?", "What is the difference between custom quizzes and entry tests like MDCAT/ECAT?"]
  },
  {
    question: "What is MDCAT preparation in your app?",
    answer: "It’s a special quiz mode where our AI generates questions based on the official MDCAT syllabus and past paper standards. These quizzes follow the structure, pattern, and difficulty of the real entry test.",
    related: ["What is ECAT prep?", "What is the difference between custom quizzes and entry tests like MDCAT/ECAT?"]
  },
  {
    question: "What is ECAT prep?",
    answer: "Similar to MDCAT prep, our ECAT module provides syllabus-specific quizzes for Physics, Chemistry, Math, and English, designed to match the difficulty and format of the engineering entry test.",
    related: ["What is MDCAT preparation?", "What are standard-based tests?"]
  },
  {
    question: "Why do emails go to spam?",
    answer: "Emails can go to spam if they contain certain keywords, come from a new sender, or if your email provider's filter is very strict. It's always a good idea to check your spam folder for important emails.",
    related: ["What is the spam folder?", "I didn’t receive my verification email."]
  }
];

export const initialQuestions = [
    "I didn’t receive my verification email. What should I do?",
    "What is the difference between custom quizzes and entry tests like MDCAT/ECAT?",
    "What is a study guide?",
    "How to use the Quiz from Document feature?"
];
