
export type FAQ = {
    question: string;
    answer: string;
    related: string[];
};

export const faqs: FAQ[] = [
  {
    question: "I didn’t receive my verification email. What should I do?",
    answer: "First, check your spam or junk folder. If you still can't find it, go to the login page, enter your credentials, and a 'Resend verification email' link will appear. Click that to get a new link.",
    related: ["How to verify my email?", "What are custom quizzes?", "How do I contact support?"]
  },
  {
    question: "How to verify my email?",
    answer: "After signing up, open the verification email we sent you and click the link inside. This activates your account. If you don't see the email, check your spam folder.",
    related: ["I didn’t receive my verification email.", "What are custom quizzes?", "How to get the best results from the AI?"]
  },
  {
    question: "What are custom quizzes?",
    answer: "Custom quizzes are tests generated by our AI based on your specific inputs. You can enter any topic (e.g., 'The Calvin Cycle'), set the difficulty, number of questions, and format (Multiple Choice or Descriptive) for a truly personalized study session.",
    related: ["What is the difference between practice questions and custom quizzes?", "What is a study guide?", "What is the difference between custom quizzes and entry tests?"]
  },
  {
    question: "What is the difference between practice questions and custom quizzes?",
    answer: "Practice questions are for quick revisions on a set topic and always come with detailed AI-generated explanations. Custom quizzes are dynamically generated tests based on any topic you provide, focusing on assessment.",
    related: ["What are custom quizzes?", "How do I generate a quiz from a document?", "What is a study guide?"]
  },
  {
    question: "What is a study guide?",
    answer: "An AI-generated study guide is a comprehensive document that breaks down any topic. It includes a summary, key concepts with definitions, simple analogies to explain complex ideas, and a quick self-quiz to check your understanding.",
    related: ["What are custom quizzes?", "How do I generate a quiz from a document?", "What is the difference between practice questions and custom quizzes?"]
  },
  {
    question: "What is the difference between custom quizzes and entry tests?",
    answer: "In custom quizzes, you can enter any topic and the AI generates relevant questions. In Entry Test mode (MDCAT, ECAT, NTS), the AI generates questions that strictly follow the official syllabus, format, and difficulty for that specific exam.",
    related: ["What are custom quizzes?", "What is MDCAT preparation?", "What is ECAT prep?"]
  },
  {
    question: "How do I generate a quiz from a document?",
    answer: "Go to 'Quiz from Document', upload your file (PDF, DOCX), select the number of questions you want, and our AI will create a quiz based *only* on the content of your document. It's perfect for studying your own notes.",
    related: ["What are custom quizzes?", "What is a study guide?", "What is the exam paper generator?"]
  },
  {
    question: "What is the exam paper generator?",
    answer: "This is a powerful tool for educators. You can input paper details (school name, marks, etc.), set content parameters (topic, difficulty), and generate multiple variants of a professional, print-ready exam paper with an automatic answer key.",
    related: ["How do I generate a quiz from a document?", "What are custom quizzes?", "What is a study guide?"]
  },
  {
    question: "What is MDCAT preparation?",
    answer: "It’s a special module where our AI generates chapter-wise and full-length mock tests based on the official MDCAT syllabus and past paper standards. It covers Biology, Chemistry, Physics, English, and Logical Reasoning.",
    related: ["What is ECAT prep?", "What is NTS prep?", "What is the difference between custom quizzes and entry tests?"]
  },
  {
    question: "What is ECAT prep?",
    answer: "Similar to MDCAT prep, our ECAT module provides syllabus-specific practice tests for Physics, Mathematics, English, and the optional subjects (Chemistry or Computer Science). A full-length mock test is also available.",
    related: ["What is MDCAT preparation?", "What is NTS prep?", "What is the difference between custom quizzes and entry tests?"]
  },
  {
    question: "What is NTS prep?",
    answer: "This module helps you prepare for various NAT categories (e.g., Pre-Engineering, Pre-Medical). It offers tests for the subject portions based on your selected field, plus a comprehensive mock test covering all sections (Analytical, Quantitative, Verbal, and Subject).",
    related: ["What is MDCAT preparation?", "What is ECAT prep?", "What is the difference between custom quizzes and entry tests?"]
  },
  {
    question: "What does the 'AI is overloaded' error mean?",
    answer: "This means the AI model is currently handling a high volume of requests from many users. It's a temporary issue. Please wait a few moments and try generating your content again.",
    related: ["What is the limit of questions per session?", "How to get the best results from the AI?", "Is the app free?"]
  },
  {
    question: "What is the limit of questions per session?",
    answer: "You can generate up to 55 questions in a single request. Please note that for very complex or niche topics, the AI may sometimes generate a slightly different number of questions than requested.",
    related: ["What does the 'AI is overloaded' error mean?", "How to get the best results from the AI?", "Is the app free?"]
  },
  {
    question: "What is the limit of questions per day?",
    answer: "Currently, Quizzicallabs AI is completely free to use, and there are no daily limits on the number of questions or guides you can generate. Enjoy!",
    related: ["What is the limit of questions per session?", "Is the app free?", "How do I contact support?"]
  },
  {
    question: "How to get the best results from the AI?",
    answer: "Be specific! Instead of just 'Biology', try 'Cellular Respiration in Eukaryotes' or 'MDCAT Physics - Electromagnetism'. The more detailed your topic and instructions, the better and more accurate the AI's response will be.",
    related: ["What are custom quizzes?", "What is the difference between custom quizzes and entry tests?"]
  },
  {
    question: "Is the app free?",
    answer: "Yes, currently all features of Quizzicallabs AI are free to use. We support the service through on-site advertising.",
    related: ["What is the limit of questions per day?", "How do I contact support?"]
  },
  {
    question: "What is spam?",
    answer: "The spam folder is where your email provider sends suspicious or promotional emails. Sometimes verification emails also land here. In Gmail, you can find it by opening the menu (three lines in the top-left) and scrolling down to 'Spam'.",
    related: ["How to verify my email?", "I didn’t receive my verification email."]
  },
  {
    question: "How do I contact support?",
    answer: "I'm sorry I couldn't resolve your issue. For direct assistance, you can reach out to our team via WhatsApp for the quickest response at +923297642797, or email us at support@quizzicallabz.qzz.io.",
    related: ["I didn’t receive my verification email.", "What does the 'AI is overloaded' error mean?"]
  }
];

export const initialQuestions = [
    "I didn’t receive my verification email. What should I do?",
    "What is the difference between custom quizzes and entry tests?",
    "How do I generate a quiz from a document?",
    "How do I contact support?",
];
