// Centralized icon imports to prevent missing import errors
export {
  Crown,
  Trophy,
  Medal,
  Flame,
  Star,
  Sword,
  Target,
  Zap,
  Users,
  Clock,
  Play,
  Settings,
  Plus,
  Lock,
  Globe,
  Sparkles,
  AlertTriangle,
  ArrowLeft,
  Gamepad2,
  Layers,
  Rocket,
  Radar,
  ChevronDown,
  CheckCircle,
  X,
  Timer,
  LogOut,
  WifiOff,
  Loader2,
  TrendingUp,
  Award,
  Calendar,
  Bookmark,
  Brain,
  BarChart,
  BookOpenText,
  PlusSquare,
  BookMarked,
  Keyboard,
  Shield
} from 'lucide-react';

// Re-export for easy access
import * as LucideIcons from 'lucide-react';

export const Icons = {
  Crown: LucideIcons.Crown,
  Trophy: LucideIcons.Trophy,
  Medal: LucideIcons.Medal,
  Flame: LucideIcons.Flame,
  Star: LucideIcons.Star,
  Sword: LucideIcons.Sword,
  Target: LucideIcons.Target,
  Zap: LucideIcons.Zap,
  Users: LucideIcons.Users,
  Clock: LucideIcons.Clock,
  Play: LucideIcons.Play,
  Settings: LucideIcons.Settings,
  Plus: LucideIcons.Plus,
  Lock: LucideIcons.Lock,
  Globe: LucideIcons.Globe,
  Sparkles: LucideIcons.Sparkles,
  AlertTriangle: LucideIcons.AlertTriangle,
  ArrowLeft: LucideIcons.ArrowLeft,
  Gamepad2: LucideIcons.Gamepad2,
  Layers: LucideIcons.Layers,
  Rocket: LucideIcons.Rocket,
  Radar: LucideIcons.Radar,
  ChevronDown: LucideIcons.ChevronDown,
  CheckCircle: LucideIcons.CheckCircle,
  X: LucideIcons.X,
  Timer: LucideIcons.Timer,
  LogOut: LucideIcons.LogOut,
  WifiOff: LucideIcons.WifiOff,
  Loader2: LucideIcons.Loader2,
  TrendingUp: LucideIcons.TrendingUp,
  Award: LucideIcons.Award,
  Calendar: LucideIcons.Calendar,
  Bookmark: LucideIcons.Bookmark,
  Brain: LucideIcons.Brain,
  BarChart: LucideIcons.BarChart,
  BookOpenText: LucideIcons.BookOpenText,
  PlusSquare: LucideIcons.PlusSquare,
  BookMarked: LucideIcons.BookMarked,
  Keyboard: LucideIcons.Keyboard,
  Shield: LucideIcons.Shield
};