// @ts-nocheck
import { NextRequest, NextResponse } from 'next/server';

interface ErrorReport {
  message: string;
  stack?: string;
  level: 'error' | 'warning' | 'info';
  context: {
    userId?: string;
    userAgent?: string;
    url?: string;
    timestamp: string;
    sessionId?: string;
    buildVersion?: string;
    environment: string;
  };
  fingerprint?: string;
  tags?: Record<string, string>;
}

export async function POST(request: NextRequest) {
  try {
    const errorReport: ErrorReport = await request.json();

    // Validate required fields
    if (!errorReport.message || !errorReport.level) {
      return NextResponse.json(
        { error: 'Missing required fields: message, level' },
        { status: 400 }
      );
    }

    // Log error to console (in production, this would go to your logging service)
    console.error('Error Report Received:', {
      message: errorReport.message,
      level: errorReport.level,
      fingerprint: errorReport.fingerprint,
      timestamp: errorReport.context.timestamp,
      url: errorReport.context.url,
      userId: errorReport.context.userId,
      environment: errorReport.context.environment
    });

    // In production, you would:
    // 1. Store in database for analysis
    // 2. Send to external monitoring service (Sentry, LogRocket, etc.)
    // 3. Trigger alerts for critical errors
    // 4. Update error metrics

    // Store in Firebase for analysis (optional)
    if (process.env.NODE_ENV === 'production') {
      try {
        const { db } = await import('@/lib/firebase-admin');
        await db.collection('error_reports').add({
          ...errorReport,
          receivedAt: new Date().toISOString(),
          processed: false
        });
      } catch (dbError) {
        console.error('Failed to store error in database:', dbError);
        // Don't fail the request if database storage fails
      }
    }

    // Send email alert for critical errors
    if (errorReport.level === 'error' && process.env.NODE_ENV === 'production') {
      try {
        await sendCriticalErrorAlert(errorReport);
      } catch (alertError) {
        console.error('Failed to send error alert:', alertError);
      }
    }

    return NextResponse.json({ 
      success: true, 
      fingerprint: errorReport.fingerprint 
    });

  } catch (error: any) {
    console.error('Error processing error report:', error);
    return NextResponse.json(
      { error: 'Failed to process error report' },
      { status: 500 }
    );
  }
}

async function sendCriticalErrorAlert(errorReport: ErrorReport) {
  // Send email alert for critical errors
  const alertData = {
    to: process.env.ADMIN_EMAIL || 'admin@quizzicallabz.qzz.io',
    subject: `🚨 Critical Error Alert - QuizzicalLabzᴬᴵ`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #dc2626;">🚨 Critical Error Detected</h2>
        
        <div style="background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px; padding: 16px; margin: 16px 0;">
          <h3 style="color: #991b1b; margin-top: 0;">Error Details</h3>
          <p><strong>Message:</strong> ${errorReport.message}</p>
          <p><strong>Level:</strong> ${errorReport.level}</p>
          <p><strong>Timestamp:</strong> ${errorReport.context.timestamp}</p>
          <p><strong>URL:</strong> ${errorReport.context.url || 'N/A'}</p>
          <p><strong>User ID:</strong> ${errorReport.context.userId || 'Anonymous'}</p>
          <p><strong>Environment:</strong> ${errorReport.context.environment}</p>
          <p><strong>Fingerprint:</strong> ${errorReport.fingerprint}</p>
        </div>

        ${errorReport.stack ? `
          <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin: 16px 0;">
            <h3 style="color: #374151; margin-top: 0;">Stack Trace</h3>
            <pre style="white-space: pre-wrap; font-size: 12px; color: #6b7280;">${errorReport.stack}</pre>
          </div>
        ` : ''}

        <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 16px; margin: 16px 0;">
          <h3 style="color: #1e40af; margin-top: 0;">Quick Actions</h3>
          <p>
            <a href="https://quizzicallabz.qzz.io/api/health" style="color: #2563eb;">Check System Health</a> |
            <a href="https://vercel.com/dashboard" style="color: #2563eb;">View Deployment Logs</a> |
            <a href="https://console.firebase.google.com" style="color: #2563eb;">Check Firebase Console</a>
          </p>
        </div>

        <p style="color: #6b7280; font-size: 14px;">
          This alert was automatically generated by the QuizzicalLabzᴬᴵ error monitoring system.
        </p>
      </div>
    `
  };

  // Send via your email service
  const response = await fetch(`${process.env.NEXT_PUBLIC_APP_URL}/api/send-email`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(alertData)
  });

  if (!response.ok) {
    throw new Error(`Failed to send alert email: ${response.status}`);
  }
}

// GET endpoint to retrieve error statistics (for admin dashboard)
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const timeframe = searchParams.get('timeframe') || '24h';
    
    // In production, you would query your database for error statistics
    // For now, return mock data structure
    const stats = {
      total_errors: 0,
      error_rate: 0,
      top_errors: [],
      error_trends: [],
      timeframe
    };

    return NextResponse.json(stats);

  } catch (error: any) {
    console.error('Error retrieving error statistics:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve error statistics' },
      { status: 500 }
    );
  }
}