
import { PageHeader } from '@/components/page-header';
import { Card, CardContent } from '@/components/ui/card';
import Link from 'next/link';

export default function TermsOfUsePage() {
  return (
    <div className="container py-8 max-w-4xl mx-auto">
      <PageHeader title="Terms of Use" description="Last updated: July 30, 2024" />
      <Card className="bg-muted/30">
        <CardContent className="pt-6 space-y-6 text-sm text-muted-foreground leading-relaxed">
          <p>
            Welcome to Quizzicallabs AI. These Terms of Use ("Terms") govern your access to and use of our application and services ("Service"), which are a product of QuizzicalLabs™. By accessing or using our Service, you agree to be bound by these Terms.
          </p>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-foreground">1. Accounts</h2>
            <p>When you create an account with us, you guarantee that you are above the age of 5 and that the information you provide is accurate, complete, and current. You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password. You agree to notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-foreground">2. Use of AI-Generated Content</h2>
            <p>Our Service uses artificial intelligence to generate content, including quizzes, study guides, and explanations ("AI Content"). You acknowledge that AI Content is probabilistic and may contain inaccuracies, errors, or omissions. It is provided for educational and informational purposes only and is not a substitute for professional academic instruction or verified educational materials.</p>
            <p>QuizzicalLabs™ does not guarantee the accuracy, completeness, or reliability of any AI Content. You are solely responsible for verifying the information before relying on it for academic, professional, or other critical purposes. You agree to use the AI Content at your own risk. Please see our <Link href="/disclaimer" className="text-primary hover:underline">Disclaimer</Link> for more information.</p>
          </div>
          
           <div className="space-y-2">
            <h2 className="text-xl font-semibold text-foreground">3. User Conduct and Responsibilities</h2>
            <p>You agree not to use the Service:</p>
             <ul className="list-disc list-inside pl-4 space-y-1">
                <li>In any way that violates any applicable national or international law or regulation.</li>
                <li>To generate content that is defamatory, obscene, pornographic, abusive, or that infringes on any third party's rights, including intellectual property rights.</li>
                <li>For any form of academic dishonesty. The AI-generated content is a study aid, not a tool for cheating.</li>
                <li>To attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Service, the server on which the Service is stored, or any server, computer, or database connected to the Service.</li>
                <li>To reverse-engineer, decompile, or otherwise attempt to discover the source code or underlying algorithms of the Service.</li>
            </ul>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-foreground">4. Intellectual Property</h2>
            <p>The Service and its original content (excluding content generated by users), features, and functionality are and will remain the exclusive property of QuizzicalLabs™ and its licensors. Our trademarks may not be used in connection with any product or service without prior written consent. You retain ownership of the documents you upload, but you grant us a temporary, non-exclusive license to use that content solely for the purpose of providing the Service to you.</p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-foreground">5. Termination</h2>
            <p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease.</p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-foreground">6. Limitation of Liability and Disclaimer of Warranties</h2>
            <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. To the fullest extent permissible by law, QuizzicalLabs™ disclaims all warranties, express or implied, in connection with the Service and your use thereof. We do not warrant that the Service will be uninterrupted, secure, or error-free.</p>
             <p>In no event shall QuizzicalLabs™, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-foreground">7. Changes to Terms</h2>
            <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of material changes by posting the new Terms on this page and updating the "Last updated" date.</p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-foreground">Contact Us</h2>
            <p>If you have any questions about these Terms, please contact us at legal@quizzicallabs.com.</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
