"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import * as z from "zod";
import { AnimatePresence, motion } from "framer-motion";
import { Clock } from "lucide-react";
import { Sparkles } from "lucide-react";
import { BrainCircuit, Loader2, CheckCircle, XCircle, MessageSquareQuote, Star, Download, Redo, RefreshCw, Brain, Lightbulb, LayoutDashboard, ArrowLeft, ArrowRight } from "lucide-react";
import { useForm, FormProvider } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import dynamic from "next/dynamic";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useAuth";
import { usePlan } from "@/hooks/usePlan";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import RichContentRenderer from "@/components/rich-content-renderer";

// Dynamic imports for code splitting
const QuizSetupForm = dynamic(() => import('@/components/quiz-wizard/quiz-setup-form'), {
  loading: () => <QuizLoadingSkeleton />,
});

const QuizTaker = dynamic(() => import('@/components/quiz-wizard/quiz-taker'), {
  loading: () => <QuizLoadingSkeleton />,
});

const QuizResults = dynamic(() => import('@/components/quiz-wizard/quiz-results'), {
  loading: () => <QuizLoadingSkeleton />,
});

const FlashcardViewer = dynamic(() => import('@/components/quiz-wizard/flashcard-viewer'), {
  loading: () => <QuizLoadingSkeleton />,
});

// Import types and utilities
import type { GenerateCustomQuizOutput } from "@/ai/flows/generate-custom-quiz";
import type { GenerateFlashcardsOutput } from "@/ai/flows/generate-flashcards";
import {
    getQuizState,
    saveQuizState,
    getBookmarks,
    getQuizResults
} from "@/lib/indexed-db";

function QuizLoadingSkeleton() {
  return (
    <div className="flex flex-col items-center justify-center min-h-[60svh] text-center p-4">
      <div className="relative">
        <BrainCircuit className="h-20 w-20 text-primary" />
        <motion.div
          className="absolute inset-0 flex items-center justify-center"
          animate={{ rotate: 360 }}
          transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
        >
          <div className="h-8 w-8 border-4 border-accent border-t-transparent rounded-full animate-spin" />
        </motion.div>
      </div>
      <h2 className="text-2xl font-semibold mb-2 mt-6">Loading Quiz...</h2>
      <p className="text-muted-foreground max-w-sm">Preparing your personalized quiz experience.</p>
    </div>
  );
}

const formSchema = z.object({
  topic: z.string().min(1, "Topic is required."),
  difficulty: z.enum(["easy", "medium", "hard", "master"]),
  numberOfQuestions: z.number().min(1).max(55),
  questionTypes: z.array(z.string()).refine((value) => value.some((item) => item), {
    message: "You have to select at least one question type.",
  }),
  questionStyles: z.array(z.string()).refine((value) => value.some((item) => item), {
    message: "You have to select at least one question style.",
  }),
  timeLimit: z.number().min(1).max(120),
  specificInstructions: z.string().optional(),
});

export type QuizFormValues = z.infer<typeof formSchema>;
export type Quiz = GenerateCustomQuizOutput["quiz"];
type Flashcard = GenerateFlashcardsOutput["flashcards"][0];

interface ExplanationState {
  [questionIndex: number]: {
    isLoading: boolean;
    explanation: string | null;
    isSimpleLoading: boolean;
    simpleExplanation: string | null;
  };
}

const addPdfHeaderAndFooter = (doc: any, title: string, difficulty: string, isPro: boolean) => {
    const pageCount = (doc as any).internal.getNumberOfPages();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);

        // Header
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(16);
        doc.text("Quizzicallabs™", pageWidth / 2, 15, { align: 'center' });

        doc.setFontSize(14);
        doc.text(`Quiz Topic: ${title}`, pageWidth / 2, 25, { align: 'center' });

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.text(`Difficulty: ${difficulty}`, pageWidth / 2, 31, { align: 'center' });

        doc.setLineWidth(0.2);
        doc.line(20, 38, pageWidth - 20, 38);

        // Watermark for free users
        if (!isPro) {
            doc.saveGraphicsState();
            doc.setFontSize(60);
            doc.setTextColor(230, 230, 230);
            doc.setGState(new (doc as any).GState({opacity: 0.5}));
            doc.text("Quizzicallabs AI", pageWidth / 2, pageHeight / 2, { angle: 45, align: 'center' });
            doc.restoreGraphicsState();
        }

        // Footer
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setLineWidth(0.2);
        doc.line(20, pageHeight - 18, pageWidth - 20, pageHeight - 18);
        doc.text(`Generated by Quizzicallabs™ - A Project By Absar Ahmad Rao`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    }
}

type GenerateQuizPageProps = {
  initialQuiz?: Quiz;
  initialFormValues?: QuizFormValues;
  initialComprehensionText?: string;
}

// --- Main Page Component ---
export default function GenerateQuizPage({ initialQuiz, initialFormValues, initialComprehensionText }: GenerateQuizPageProps) {
  const { toast } = useToast();
  const { user } = useAuth();
  const { isPro } = usePlan();
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationProgress, setGenerationProgress] = useState(0);

  const [quiz, setQuiz] = useState<Quiz | null>(null);
  const [comprehensionText, setComprehensionText] = useState<string | null>(null);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [userAnswers, setUserAnswers] = useState<(string | null)[]>([]);
  const [showResults, setShowResults] = useState(false);
  const [explanations, setExplanations] = useState<ExplanationState>({});

  const [formValues, setFormValues] = useState<QuizFormValues | null>(null);
  const [timeLeft, setTimeLeft] = useState(0);

  const [isGeneratingFlashcards, setIsGeneratingFlashcards] = useState(false);
  const [generatedFlashcards, setGeneratedFlashcards] = useState<Flashcard[] | null>(null);
  const [showFlashcardViewer, setShowFlashcardViewer] = useState(false);


  const timerRef = useRef<NodeJS.Timeout | null>(null);
  const hasInitialized = useRef(false);

  const formMethods = useForm<QuizFormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      topic: "",
      difficulty: "medium",
      numberOfQuestions: 10,
      questionTypes: ["Multiple Choice"],
      questionStyles: ["Knowledge-based", "Conceptual"],
      timeLimit: 10,
      specificInstructions: "",
    },
  });

  const calculateScore = useCallback(() => {
    if (!quiz) return { score: 0, percentage: 0, totalScorable: 0 };
    const score = quiz.reduce((acc, question, index) => {
      const userAnswer = userAnswers[index];
      const correctAnswer = question.correctAnswer;
      if (question.type === 'descriptive' || correctAnswer === undefined) {
        return acc;
      }
      return acc + (correctAnswer === userAnswer ? 1 : 0);
    }, 0);

    const scorableQuestions = quiz.filter(q => q.type !== 'descriptive' && q.correctAnswer !== undefined).length;
    const percentage = scorableQuestions > 0 ? (score / scorableQuestions) * 100 : 0;

    return { score, percentage, totalScorable: scorableQuestions };
  }, [quiz, userAnswers]);


  const handleSubmit = useCallback(async () => {
    if ((window as any).__MOCK_TEST_SUBMIT_OVERRIDE__) {
        (window as any).__MOCK_TEST_SUBMIT_OVERRIDE__(userAnswers);
        return;
    }

    setShowResults(true);
    if(quiz && formValues && user) {
        const { score, percentage } = calculateScore();
        const resultId = `${user.uid}-${Date.now()}`;
        const newResult = {
            id: resultId,
            userId: user.uid,
            topic: formValues.topic,
            score,
            total: quiz.length,
            percentage,
            date: new Date().toISOString(),
        };
        const resultRef = ref(db, `quizResults/${user.uid}/${resultId}`);
        await set(resultRef, newResult);
        await saveQuizResult(newResult);
        await deleteQuizState(user.uid);
    }
    window.scrollTo(0, 0);
  }, [quiz, userAnswers, formValues, user, calculateScore]);


  useEffect(() => {
    const initializeQuiz = async () => {
        if (hasInitialized.current) return;
        hasInitialized.current = true;

        const mockTestAnswers = (window as any).__MOCK_TEST_ANSWERS__;
        if (initialQuiz && initialFormValues && mockTestAnswers) {
            setQuiz(initialQuiz);
            setFormValues(initialFormValues);
            setUserAnswers(mockTestAnswers);
            setShowResults(true);
            delete (window as any).__MOCK_TEST_ANSWERS__;
            return;
        }

        if (initialQuiz && initialFormValues) {
            setQuiz(initialQuiz);
            setComprehensionText(initialComprehensionText || null);
            setUserAnswers(new Array(initialQuiz.length).fill(null));
            setTimeLeft(initialFormValues.timeLimit * 60);
            setFormValues(initialFormValues);
            setShowResults(false);
            return;
        }

        if (user) {
            const savedState = await getQuizState(user.uid);
            if (savedState && savedState.quiz && savedState.formValues) {
                setQuiz(savedState.quiz);
                setComprehensionText(savedState.comprehensionText || null);
                setCurrentQuestion(savedState.currentQuestion);
                setUserAnswers(savedState.userAnswers);
                setTimeLeft(savedState.timeLeft);
                setFormValues(savedState.formValues);
                setShowResults(false);
                return;
            }
        }

        setQuiz(null);
        setShowResults(false);
    };

    initializeQuiz();
  }, [user, initialQuiz, initialFormValues, initialComprehensionText]);


  const [bookmarkedQuestions, setBookmarkedQuestions] = useState<BookmarkedQuestion[]>([]);

  useEffect(() => {
    async function loadBookmarks() {
        if (user) {
            const bookmarks = await getBookmarks(user.uid);
            setBookmarkedQuestions(bookmarks);
        }
    }
    loadBookmarks();
  }, [user]);

  useEffect(() => {
    async function persistState() {
        if (user && quiz && !showResults && !initialQuiz) {
            await saveQuizState(user.uid, {
                quiz,
                comprehensionText,
                currentQuestion,
                userAnswers,
                timeLeft,
                formValues,
            });
        }
    }
    persistState();
  }, [quiz, comprehensionText, currentQuestion, userAnswers, timeLeft, formValues, showResults, user, initialQuiz]);


  useEffect(() => {
    if (quiz && !showResults && timeLeft > 0) {
      // Clear any existing timer before starting a new one
      if (timerRef.current) {
        clearInterval(timerRef.current);
      }

      timerRef.current = setInterval(() => {
        setTimeLeft((prevTime) => {
          if (prevTime <= 1) {
            if (timerRef.current) clearInterval(timerRef.current);
            handleSubmit();
            return 0;
          }
          return prevTime - 1;
        });
      }, 1000);
    }

    // Cleanup function to clear the interval when the component unmounts
    // or when the dependencies change.
    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current);
      }
    };
  }, [quiz, showResults, timeLeft, handleSubmit]);

  const handleGenerateQuiz = async (values: QuizFormValues) => {
    setIsGenerating(true);
    setFormValues(values);
    setGenerationProgress(0);

    const interval = setInterval(() => {
        setGenerationProgress(prev => {
            if (prev >= 95) {
                clearInterval(interval);
                return prev;
            }
            return prev + 5;
        })
    }, 500);

    setQuiz(null);
    setComprehensionText(null);
    setCurrentQuestion(0);
    setUserAnswers([]);
    setShowResults(false);
    setExplanations({});

    try {
      const recentQuizHistory = user ? (await getQuizResults(user.uid)).slice(0, 5) : [];
      const historyForAI = recentQuizHistory.map(r => ({ topic: r.topic, percentage: r.percentage }));

      const response = await fetch("/api/generate-quiz", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ...values,
          isPro: isPro,
          userAge: user?.age,
          userClass: user?.className,
          recentQuizHistory: historyForAI,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate quiz");
      }

      const result = await response.json();
      clearInterval(interval);
      setGenerationProgress(100);

      setTimeout(() => {
        if (!result.quiz || result.quiz.length === 0) {
           throw new Error("The AI returned an empty quiz. This can happen with very niche topics. Please try broadening your topic or rephrasing your instructions.");
        }
        setQuiz(result.quiz);
        setComprehensionText(result.comprehensionText || null);
        setUserAnswers(new Array(result.quiz.length).fill(null));
        setTimeLeft(values.timeLimit * 60);
        setIsGenerating(false);
        setFormValues(values);
      }, 500)

    } catch (error: any) {
        clearInterval(interval);
        setIsGenerating(false);
        setFormValues(null);
        let errorMessage = "An unexpected response was received from the server.";
        if (error.message && (error.message.includes("503") || error.message.includes("overloaded"))) {
          errorMessage = "The AI model is currently overloaded. Please wait a moment and try again.";
        } else if (error?.message?.includes("429")) {
            errorMessage = "You have hit a rate limit. Please try again after some time.";
        } else if (error.message && !error.message.includes('Unexpected')) {
            errorMessage = error.message;
        }
      toast({
        title: "Error Generating Quiz",
        description: errorMessage,
        variant: "destructive",
      });
      console.error(error);
    }
  };


  const handleAnswer = (answer: string) => {
    const newAnswers = [...userAnswers];
    newAnswers[currentQuestion] = answer;
    setUserAnswers(newAnswers);
  };

  const handleNext = () => {
    if (currentQuestion < (quiz?.length ?? 0) - 1) {
      setCurrentQuestion(currentQuestion + 1);
    } else {
      handleSubmit();
    }
  };

  const handleBack = () => {
    if (currentQuestion > 0) {
      setCurrentQuestion(currentQuestion - 1);
    }
  };

  const getExplanation = async (questionIndex: number) => {
    if (!quiz || !formValues) return;
    const question = quiz[questionIndex];
    setExplanations((prev) => ({
      ...prev,
      [questionIndex]: { ...prev[questionIndex], isLoading: true, explanation: null },
    }));

    try {
      const response = await fetch("/api/generate-explanation", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          question: question.question,
          studentAnswer: userAnswers[questionIndex] || "",
          correctAnswer: question.correctAnswer || "N/A",
          topic: formValues.topic,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate explanation");
      }

      const result = await response.json();
      setExplanations((prev) => ({
        ...prev,
        [questionIndex]: { ...prev[questionIndex], isLoading: false, explanation: result.explanation },
      }));
    } catch (error) {
      toast({
        title: "Error Generating Explanation",
        description: "An error occurred while generating the explanation. Please try again.",
        variant: "destructive",
      });
       setExplanations((prev) => ({
        ...prev,
        [questionIndex]: { ...prev[questionIndex], isLoading: false, explanation: "Could not load explanation." },
      }));
      console.error(error);
    }
  };

  const getSimpleExplanation = async (questionIndex: number) => {
    if (!quiz || !formValues) return;
    const question = quiz[questionIndex];
    setExplanations((prev) => ({
      ...prev,
      [questionIndex]: { ...prev[questionIndex], isSimpleLoading: true, simpleExplanation: null },
    }));

    try {
      const response = await fetch("/api/generate-simple-explanation", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          question: question.question,
          correctAnswer: question.correctAnswer || "N/A",
          topic: formValues.topic,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate simple explanation");
      }

      const result = await response.json();
      setExplanations((prev) => ({
          ...prev,
          [questionIndex]: { ...prev[questionIndex], isSimpleLoading: false, simpleExplanation: result.explanation },
      }));
    } catch (error) {
        toast({
            title: "Error Simplifying",
            description: "Could not generate a simpler explanation at this time.",
            variant: "destructive",
        });
        setExplanations((prev) => ({
            ...prev,
            [questionIndex]: { ...prev[questionIndex], isSimpleLoading: false, simpleExplanation: "Could not load simple explanation." },
        }));
    }
  }

  const handleGenerateFlashcards = async () => {
    if (!quiz || !formValues) return;
    const incorrectQuestions = quiz
        .map((q, i) => ({ ...q, userAnswer: userAnswers[i] }))
        .filter(q => q.correctAnswer !== q.userAnswer && q.type !== 'descriptive');

    if (incorrectQuestions.length === 0) {
        toast({ title: "Nothing to review!", description: "You answered all questions correctly." });
        return;
    }

    setIsGeneratingFlashcards(true);
    setGeneratedFlashcards(null);

    try {
      const response = await fetch("/api/generate-flashcards", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          topic: formValues.topic,
          incorrectQuestions: incorrectQuestions.map(q => ({
            question: q.question,
            userAnswer: q.userAnswer || null,
            correctAnswer: q.correctAnswer || '',
          }))
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate flashcards");
      }

      const result = await response.json();
      if (result.flashcards.length === 0) {
        toast({ title: "No flashcards generated", description: "The AI didn't find any concepts from your incorrect answers to turn into flashcards." });
      } else {
        setGeneratedFlashcards(result.flashcards);
        setShowFlashcardViewer(true);
      }
    } catch (error) {
        toast({ title: "Error Generating Flashcards", description: "Could not generate flashcards at this time.", variant: "destructive" });
    } finally {
        setIsGeneratingFlashcards(false);
    }
  }


  const downloadQuestions = async () => {
    if (!quiz || !formValues) return;
    const { default: jsPDF } = await import('jspdf');
    const doc = new jsPDF();
    let y = 45;
    const pageHeight = 270;
    const margin = 20;
    const maxWidth = doc.internal.pageSize.getWidth() - (margin * 2);

    const checkPageBreak = (neededHeight: number) => {
        if (y + neededHeight > pageHeight) {
            doc.addPage();
            y = 45;
        }
    };

    quiz.forEach((q, i) => {
        checkPageBreak(30);

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(12);
        doc.text(doc.splitTextToSize(`${i + 1}. ${q.question}`, maxWidth), margin, y);
        y += (doc.splitTextToSize(`${i + 1}. ${q.question}`, maxWidth).length * 5) + 5;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        if (q.answers) {
            q.answers.forEach((a, ansIndex) => {
                checkPageBreak(5);
                const letter = String.fromCharCode(65 + ansIndex);
                doc.text(doc.splitTextToSize(`${letter}. ${a}`, maxWidth - 5), margin + 5, y);
                y += (doc.splitTextToSize(`- ${a}`, maxWidth - 5).length * 4) + 3;
            });
        }

        y += 5;
    });

    if (formValues.questionTypes.includes('Multiple Choice')) {
        doc.addPage();
        y = 45;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.text("Answer Key", margin, y);
        y += 10;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        quiz.forEach((q, i) => {
            if(q.type === 'multiple-choice') {
                checkPageBreak(5);
                 const correctAnswerLetter = String.fromCharCode(65 + (q.answers?.findIndex(ans => ans === q.correctAnswer) ?? 0));
                doc.text(`${i + 1}. ${correctAnswerLetter}`, margin, y);
                y += 6;
            }
        });
    }

    addPdfHeaderAndFooter(doc, formValues.topic, formValues.difficulty, isPro);
    doc.save(`${formValues.topic.replace(/\s+/g, '_')}_quiz.pdf`);
  };

  const downloadResultCard = async () => {
    if (!quiz || !formValues) return;
    const { default: jsPDF } = await import('jspdf');
    const { score, percentage, totalScorable } = calculateScore();
    const doc = new jsPDF();

    addPdfHeaderAndFooter(doc, "Quiz Result Card", formValues.difficulty, isPro);

    let y = 50;

    doc.setFontSize(14);
    doc.text(`Student: ${user?.displayName || 'N/A'}`, 20, y);
    y += 10;
    doc.text(`Topic: ${formValues.topic}`, 20, y);
    y += 15;

    doc.setFontSize(16);
    doc.text(`Score: ${score}/${totalScorable}`, 20, y);
    y += 10;
    doc.text(`Percentage: ${percentage.toFixed(0)}%`, 20, y);
    y += 10;
    doc.text(`Status: ${percentage >= 50 ? 'Pass' : 'Fail'}`, 20, y);

    doc.save('quiz_result_card.pdf');
  };

  const toggleBookmark = async (question: string, correctAnswer: string) => {
    if(!formValues || !user) return;

    const isCurrentlyBookmarked = bookmarkedQuestions.some(bm => bm.question === question);
    const bookmarkId = btoa(question); // Use base64 encoded question as a safe key

    if (isCurrentlyBookmarked) {
        // Remove from Firebase and local state
        const bookmarkRef = ref(db, `bookmarks/${user.uid}/${bookmarkId}`);
        await set(bookmarkRef, null);
        await deleteBookmark(user.uid, question);
        setBookmarkedQuestions(prev => prev.filter(bm => bm.question !== question));
    } else {
        const newBookmark: BookmarkedQuestion = {
            userId: user.uid,
            question,
            correctAnswer,
            topic: formValues.topic
        };
        // Save to Firebase and local state
        const bookmarkRef = ref(db, `bookmarks/${user.uid}/${bookmarkId}`);
        await set(bookmarkRef, newBookmark);
        await saveBookmark(newBookmark);
        setBookmarkedQuestions(prev => [...prev, newBookmark]);
    }
  };

  const resetQuiz = async () => {
    if(initialQuiz) {
        // Check which prep section this quiz came from and redirect accordingly
        if (window.location.pathname.includes('/mdcat/')) {
           window.location.href = '/mdcat';
        } else if (window.location.pathname.includes('/ecat/')) {
            window.location.href = '/ecat';
        } else if (window.location.pathname.includes('/nts/')) {
            window.location.href = '/nts';
        } else {
            // Fallback for other initial quizzes
            window.location.href = '/exam-prep';
        }
        return;
    }
    if (user) {
        await deleteQuizState(user.uid);
    }
    setQuiz(null);
    setCurrentQuestion(0);
    setUserAnswers([]);
    setShowResults(false);
    setExplanations({});
    setFormValues(null);
    formMethods.reset();
    window.scrollTo(0, 0);
  };

  const retryIncorrect = () => {
    if (!quiz || !formValues) return;
    const incorrectQuestions = quiz.filter((q, i) => q.correctAnswer !== userAnswers[i] && q.type !== 'descriptive');
    if (incorrectQuestions.length === 0) {
        toast({
            title: "No incorrect answers!",
            description: "You got everything right. Well done!",
        });
        return;
    }

    const newFormValues = {
        ...formValues,
        topic: `Retry: ${formValues.topic}`,
        numberOfQuestions: incorrectQuestions.length,
        timeLimit: Math.max(5, Math.ceil(incorrectQuestions.length * 0.75)), // Adjust time limit
        questionStyles: [], // Use default styles for retry
    };

    setQuiz(incorrectQuestions);
    setFormValues(newFormValues);
    setCurrentQuestion(0);
    setUserAnswers(new Array(incorrectQuestions.length).fill(null));
    setTimeLeft(newFormValues.timeLimit * 60);
    setShowResults(false);
    setExplanations({});
    window.scrollTo(0, 0);
  };

    const formatExplanation = (text: string | null) => {
        if (!text) return null;
        return text
            .split(/(\*\*.*?\*\*)/g) // Split by bold markdown
            .map((part, index) => {
                if (part.startsWith('**') && part.endsWith('**')) {
                    return <strong key={index}>{part.slice(2, -2)}</strong>;
                }
                return part;
            });
    };

  // --- Conditional Rendering ---

  if (showFlashcardViewer) {
    return <FlashcardViewer flashcards={generatedFlashcards || []} onBack={() => setShowFlashcardViewer(false)} />;
  }


  if (isGenerating) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60svh] text-center p-4">
        <div className="relative">
            <BrainCircuit className="h-20 w-20 text-primary" />
            <motion.div
                className="absolute inset-0 flex items-center justify-center"
                animate={{ rotate: 360 }}
                transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
            >
                <Sparkles className="h-8 w-8 text-accent animate-pulse" />
            </motion.div>
        </div>
        <h2 className="text-2xl font-semibold mb-2 mt-6">Generating Your Quiz...</h2>
        <p className="text-muted-foreground max-w-sm mb-6">Please wait while our AI crafts the perfect quiz for you.</p>
        <div className="w-full max-w-sm">
           <Progress value={generationProgress} />
           <p className="text-sm mt-2 text-primary font-medium">{generationProgress}%</p>
        </div>
      </div>
    );
  }

  const cardVariants = {
    hidden: { opacity: 0, x: 20 },
    visible: { opacity: 1, x: 0 },
    exit: { opacity: 0, x: -20 },
  };

  if (quiz && !showResults) {
    const currentQ = quiz[currentQuestion];
    const progress = ((currentQuestion + 1) / quiz.length) * 100;

    return (
      <FormProvider {...formMethods}>
        <div className="flex flex-col">
            <div className="flex items-center justify-between mb-4">
                <p className="text-sm font-medium text-muted-foreground">Question {currentQuestion + 1} of {quiz.length}</p>
                <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
                    <Clock className="h-4 w-4" />
                    <span>{Math.floor(timeLeft / 60)}:{(timeLeft % 60).toString().padStart(2, '0')}</span>
                </div>
            </div>
            <Progress value={progress} className="h-2 w-full mb-6" />

           {comprehensionText && (
                <Card className="w-full max-w-4xl mx-auto mb-8 bg-muted/50">
                    <CardHeader>
                        <CardTitle>Reading Passage</CardTitle>
                        <CardDescription>Read the passage below to answer the following questions.</CardDescription>
                    </CardHeader>
                    <CardContent className="prose prose-sm dark:prose-invert max-h-48 overflow-y-auto p-4 border rounded-lg bg-background">
                        <RichContentRenderer content={comprehensionText} />
                    </CardContent>
                </Card>
            )}

          <AnimatePresence mode="wait">
              <motion.div
                  key={currentQuestion}
                  variants={cardVariants}
                  initial="hidden"
                  animate="visible"
                  exit="exit"
                  transition={{ duration: 0.3 }}
                  className="w-full"
              >
                <div className="space-y-6">
                    <div className="text-center text-xl sm:text-2xl font-semibold leading-relaxed min-h-[6rem]">
                        <RichContentRenderer content={currentQ.question} smiles={currentQ.smiles} />
                    </div>
                    <div className="w-full max-w-md mx-auto">
                      {currentQ.type === 'descriptive' ? (
                          <Textarea
                              value={userAnswers[currentQuestion] || ""}
                              onChange={(e) => handleAnswer(e.target.value)}
                              placeholder="Type your answer here..."
                              rows={5}
                              className="text-base"
                          />
                      ) : (
                          <RadioGroup
                              value={userAnswers[currentQuestion] || ""}
                              onValueChange={handleAnswer}
                              className="grid grid-cols-1 gap-3"
                          >
                              {(currentQ.answers || []).map((answer, index) => {
                              return (
                                  <FormItem key={index} className="flex flex-row items-center space-x-3 space-y-0">
                                      <FormControl>
                                        <RadioGroupItem value={answer} id={`q${currentQuestion}a${index}`} className="hidden peer" />
                                      </FormControl>
                                      <Label htmlFor={`q${currentQuestion}a${index}`} className="flex-1 text-base font-normal cursor-pointer rounded-xl border p-4 peer-data-[state=checked]:bg-primary/10 peer-data-[state=checked]:border-primary transition-all">
                                          <RichContentRenderer content={answer} />
                                      </Label>
                                  </FormItem>
                              )
                              })}
                          </RadioGroup>
                      )}
                    </div>
                </div>
              </motion.div>
          </AnimatePresence>

          <div className="mt-8 flex justify-between w-full">
            <Button onClick={handleBack} size="lg" variant="outline" disabled={currentQuestion === 0}>
                <ArrowLeft className="mr-2 h-5 w-5" />
                Back
            </Button>
            <Button onClick={handleNext} size="lg" className="bg-accent text-accent-foreground hover:bg-accent/90">
                {currentQuestion === quiz.length - 1 ? "Submit Quiz" : "Next Question"}
                {currentQuestion !== quiz.length - 1 && <ArrowRight className="ml-2 h-5 w-5" />}
            </Button>
          </div>
        </div>
      </FormProvider>
    );
  }

  if (showResults && quiz && formValues) {
    const { score, percentage, totalScorable } = calculateScore();
    const incorrectAnswers = quiz.filter((q, i) => q.correctAnswer !== userAnswers[i] && q.type !== 'descriptive');

    return (
       <div className="max-w-4xl mx-auto">
            <PageHeader title="Quiz Results" description={`You scored ${score} out of ${totalScorable}.`} />
            <Card>
                <CardHeader>
                    <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                         <CardTitle>Result Details</CardTitle>
                         <div className="flex flex-wrap gap-2">
                            <Button variant="outline" onClick={downloadQuestions}><Download className="mr-2 h-4 w-4" /> Questions</Button>
                            <Button onClick={downloadResultCard}><Download className="mr-2 h-4 w-4" /> Result Card</Button>
                         </div>
                    </div>
                </CardHeader>
                <CardContent className="pt-6">
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6 text-center">
                        <Card className="p-4 bg-muted/50">
                            <CardTitle className="text-3xl font-bold">{score}/{totalScorable}</CardTitle>
                            <CardDescription>Score</CardDescription>
                        </Card>
                         <Card className="p-4 bg-muted/50">
                            <CardTitle className="text-3xl font-bold">{percentage.toFixed(0)}%</CardTitle>
                             <CardDescription>Percentage</CardDescription>
                        </Card>
                         <Card className="p-4 bg-muted/50">
                            <CardTitle className={cn("text-3xl font-bold", percentage >= 50 ? "text-primary" : "text-destructive")}>{percentage >= 50 ? 'Pass' : 'Fail'}</CardTitle>
                             <CardDescription>Status</CardDescription>
                        </Card>
                    </div>

                    <div>
                        <h3 className="text-xl font-bold mb-4">Review Your Answers</h3>
                        <div className="space-y-4">
                            {quiz.map((q, index) => {
                                const isCorrect = q.correctAnswer === userAnswers[index];
                                const explanationState = explanations[index];
                                const isBookmarked = bookmarkedQuestions.some(bm => bm.question === q.question);

                                return (
                                    <Card key={index} className={cn("bg-muted/30", isCorrect ? "border-primary/20" : "border-destructive/20")}>
                                        <CardHeader className="flex flex-row justify-between items-start pb-2">
                                            <div className="font-semibold flex-1 pr-4"><RichContentRenderer content={`${index + 1}. ${q.question}`} smiles={q.smiles} /></div>
                                            {q.correctAnswer && (
                                                <Button variant="ghost" size="icon" onClick={() => toggleBookmark(q.question, q.correctAnswer || "")}>
                                                    <Star className={cn("h-5 w-5", isBookmarked ? "text-yellow-400 fill-yellow-400" : "text-muted-foreground")} />
                                                    <span className="sr-only">Bookmark</span>
                                                </Button>
                                            )}
                                        </CardHeader>
                                        <CardContent className="p-4 sm:p-6 pt-2">
                                            <div className="text-sm mt-2 space-y-1">
                                                 <p className={cn("flex items-start gap-2", isCorrect ? 'text-primary' : 'text-destructive')}>
                                                    {isCorrect ? <CheckCircle className="h-4 w-4 shrink-0 mt-0.5" /> : <XCircle className="h-4 w-4 shrink-0 mt-0.5" />}
                                                    <span>Your answer: <RichContentRenderer content={userAnswers[index] || "Skipped"} /></span>
                                                 </p>
                                                 {!isCorrect && q.correctAnswer && (
                                                     <p className="text-primary flex items-start gap-2">
                                                        <CheckCircle className="h-4 w-4 shrink-0 mt-0.5" />
                                                        <span>Correct answer: <RichContentRenderer content={q.correctAnswer} /></span>
                                                     </p>
                                                 )}
                                                 {q.type === 'descriptive' && !q.correctAnswer && (
                                                    <p className="flex items-start gap-2 text-muted-foreground">
                                                         <MessageSquareQuote className="h-4 w-4 shrink-0 mt-0.5" />
                                                         <span>Your Answer: {userAnswers[index] || "Not answered"}</span>
                                                    </p>
                                                 )}
                                            </div>

                                            {!isCorrect && q.type !== 'descriptive' && (
                                                <div className="mt-4 space-y-2">
                                                    {explanationState?.explanation && (
                                                        <Alert className="border-accent/50 text-accent-foreground bg-accent/10">
                                                            <AlertTitle className="text-accent-foreground/90 flex items-center gap-2"><Brain className="h-4 w-4" /> Detailed Explanation</AlertTitle>
                                                            <AlertDescription className="prose prose-sm max-w-none">{formatExplanation(explanationState.explanation)}</AlertDescription>
                                                        </Alert>
                                                    )}
                                                    {explanationState?.simpleExplanation && (
                                                         <Alert className="border-accent/50 text-accent-foreground bg-accent/10">
                                                            <AlertTitle className="text-accent-foreground/90 flex items-center gap-2"><Lightbulb className="h-4 w-4" /> Simple Explanation</AlertTitle>
                                                            <AlertDescription className="prose prose-sm max-w-none">{formatExplanation(explanationState.simpleExplanation)}</AlertDescription>
                                                         </Alert>
                                                    )}
                                                    <div className="flex flex-wrap gap-2">
                                                        <Button variant="outline" size="sm" onClick={() => getExplanation(index)} disabled={explanationState?.isLoading}>
                                                            {explanationState?.isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin"/>}
                                                            Detailed Explanation
                                                        </Button>
                                                        <Button variant="outline" size="sm" onClick={() => getSimpleExplanation(index)} disabled={explanationState?.isSimpleLoading}>
                                                            {explanationState?.isSimpleLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin"/>}
                                                            Explain Like I'm 5
                                                        </Button>
                                                    </div>
                                                </div>
                                            )}
                                        </CardContent>
                                    </Card>
                                )
                            })}
                        </div>
                    </div>
                </CardContent>
                 <CardFooter className="flex flex-wrap justify-center gap-2 pt-4 border-t">
                    <Button onClick={resetQuiz}><Redo className="mr-2 h-4 w-4" /> {initialQuiz ? 'Go to Prep Home' : 'Take Another Quiz'}</Button>
                    {incorrectAnswers.length > 0 && (
                        <Button onClick={retryIncorrect} variant="outline"><RefreshCw className="mr-2 h-4 w-4" /> Retry Incorrect</Button>
                    )}
                    {incorrectAnswers.length > 0 && (
                        <Button onClick={handleGenerateFlashcards} variant="outline" disabled={isGeneratingFlashcards}>
                            {isGeneratingFlashcards ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <Sparkles className="mr-2 h-4 w-4" />}
                            Generate Flashcards
                        </Button>
                    )}
                    <Button variant="outline" asChild><Link href="/"><LayoutDashboard className="mr-2 h-4 w-4"/> Back to Dashboard</Link></Button>
                </CardFooter>
            </Card>
       </div>
    );
  }

  return (
    <FormProvider {...formMethods}>
      <QuizSetupForm onGenerateQuiz={handleGenerateQuiz} />
    </FormProvider>
  );
}
