
import { PageHeader } from '@/components/page-header';
import { Card, CardContent } from '@/components/ui/card';
import { AlertTriangle } from 'lucide-react';

export default function DisclaimerPage() {
  return (
    <div className="container py-8 max-w-4xl mx-auto">
      <PageHeader title="Disclaimer" description="Last updated: July 30, 2024" />
      <Card className="bg-muted/30">
        <CardContent className="pt-6 space-y-6 text-sm text-muted-foreground leading-relaxed">
           <div className="flex items-start gap-4 p-4 rounded-lg bg-destructive/10 border border-destructive/20 text-destructive">
                <AlertTriangle className="h-6 w-6 mt-1 shrink-0" />
                <div>
                    <h3 className="font-bold text-destructive">Important Notice Regarding AI-Generated Content</h3>
                    <p className="mt-1">Please read this disclaimer carefully before using the services provided by Quizzicallabs™.</p>
                </div>
           </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-foreground">1. No Guarantee of Accuracy</h2>
            <p>The content generated by our application, including but not limited to quizzes, questions, answers, explanations, and study guides, is created by artificial intelligence (AI). While we strive for accuracy, AI models are probabilistic and can make mistakes, generate incorrect information, or produce content that is incomplete or misleading.</p>
            <p className="font-semibold">We do not guarantee the accuracy, completeness, or reliability of any AI-generated content.</p>
          </div>

           <div className="space-y-2">
            <h2 className="text-xl font-semibold text-foreground">2. Educational & Informational Use Only</h2>
            <p>This service is intended for educational and supplementary purposes only. It should be used as a study aid to reinforce learning and test knowledge, not as a primary source of information or a substitute for professional instruction, academic materials, or textbooks.</p>
          </div>

           <div className="space-y-2">
            <h2 className="text-xl font-semibold text-foreground">3. User Responsibility & Verification</h2>
            <p>You, the user, are solely responsible for verifying the accuracy and relevance of the information provided by the service. Before relying on any AI-generated content for exams, assignments, or any other critical purpose, you must cross-reference it with reliable and authoritative sources.</p>
            <p>Do not use content from Quizzicallabs™ as a sole source for making important decisions.</p>
          </div>
          
          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-foreground">4. Limitation of Liability</h2>
            <p>Quizzicallabs™ and its creators shall not be held liable for any errors or omissions in the content provided, nor for any damages or losses—including poor grades, academic penalties, or other adverse outcomes—that may result from the use of or reliance on the information generated by our service.</p>
          </div>

          <div className="space-y-2">
            <p>By using this application, you acknowledge and agree to these terms and accept that you use the AI-generated content at your own risk.</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
